// -- catalogue (public/catalog.json, generated by scripts/prepare-data.mjs) ----------------------

export type RewardKind = "miles" | "cashback" | "points";
export type RateUnit = "percent" | "mpd" | "points_per_dollar";
export type Period =
  | "transaction"
  | "statement_month"
  | "calendar_month"
  | "quarter"
  | "membership_year"
  | "calendar_year";

/** Month that min spend and caps are counted over: the billing cycle, or 1st to month end. */
export type SpendPeriod = "statement" | "calendar";

export interface Rule {
  id: string;
  label: string;
  rate: number;
  unit: RateUnit;
  tier: "base" | "bonus";
  allSpend: boolean;
  desc: string | null;
  minSpend: number | null;
  minSpendPeriod: Period | null;
  maxSpend: number | null;
  maxSpendPeriod: Period | null;
  cap: { amount: number; unit: "SGD_spend" | "SGD_cashback" | "miles" | "points"; period: Period } | null;
  modes: string[];
  conditions: string[];
  /** what the rule explicitly earns on: spend category keys, then transaction mode keys */
  includes: string[];
  /** filter keys the rule counts for (categories, their groups, transaction modes) */
  tags: string[];
  /** the rate only applies at named merchants or in select countries; `text` is where the terms say so */
  limit: { kind: "merchants" | "countries"; text: string } | null;
}

/** A limited-time rate, left out of `rules`; `after` is the rate its rule was kept at once it ends. */
export interface LimitedTimeRate {
  label: string;
  rate: number;
  unit: RateUnit;
  until: Ymd | null;
  text: string;
  after: number | null;
}

/** A sign-up offer: a gift (or choice of gifts) for new cardholders who meet a qualifying spend. */
export interface Bonus {
  /** "bank" or the aggregator it's offered through */
  by: string;
  title: string | null;
  desc: string;
  /** the gifts to choose between */
  options: string[];
  /** the cash option, S$ */
  value: number | null;
  /** the priciest gift's stated worth, S$ */
  worth: number | null;
  /** miles awarded by a miles gift with no stated worth */
  miles: number | null;
  minSpend: number | null;
  /** days from card approval to meet the min spend */
  withinDays: number | null;
  newToBank: boolean | null;
  /** combinable with the bank's own welcome offer */
  stackable: boolean | null;
  terms: string | null;
  validTo: string | null;
  url: string | null;
}

/** `months` is the minimum validity; `monthsMax` the upper end when it varies (alone: "up to"). */
export interface PointsExpiry {
  never: boolean;
  months: number | null;
  monthsMax: number | null;
}

export interface CatalogCard {
  id: string;
  bank: string;
  name: string;
  network: string | null;
  image: string | null;
  url: string | null;
  kind: RewardKind;
  currency: string;
  fee: { amount: number; firstYearWaived: boolean | null } | null;
  income: number | null;
  /** whether the T&Cs count monthly min spend / caps per statement or per calendar month */
  spendCycle: SpendPeriod;
  /** a source states `spendCycle`; otherwise it is the calendar-month default */
  spendCycleStated: boolean;
  /** how long points stay valid; null = not known (always null for cashback) */
  expiry: PointsExpiry | null;
  /** converting points to airline miles: `points` → `miles` per block; `fee` per conversion (0 = free, null = unknown) */
  conversion: { partner: string; points: number; miles: number; fee: number | null } | null;
  rules: Rule[];
  limitedTime: LimitedTimeRate[];
  /** categories the T&Cs explicitly exclude: spend category keys, then commonly-excluded (exclusion) keys */
  excludes: string[];
  bonuses: Bonus[];
  notes: string[];
  status: "draft" | "reviewed" | "stale";
  sources: { url: string; type: string; title: string | null }[];
}

export interface Category {
  key: string;
  label: string;
  parent: string | null;
  group: boolean;
}

export interface Catalog {
  builtAt: string;
  categories: Category[];
  exclusions: { key: string; label: string }[];
  cards: CatalogCard[];
}

// -- user data (stored on the device) ---------------------------------------------------------

/** Calendar dates are local 'YYYY-MM-DD' strings throughout. */
export type Ymd = string;

export interface SpendEntry {
  id: string;
  date: Ymd;
  amount: number;
  note?: string;
}

export interface MyCard {
  id: string;
  catalogId?: string;
  nickname: string;
  last4?: string;
  /** day of month the statement is issued (1–31, clamped to month length) */
  statementDay?: number;
  /** day of month payment is due; falls in the month after the statement if ≤ statementDay */
  dueDay?: number;
  /** annual fee billing date, 'MM-DD' */
  feeDate?: string;
  minSpend?: number;
  maxSpend?: number;
  /** user override: spend tracking resets on the statement date, or on the 1st; unset = follow the catalogue card */
  spendPeriod?: SpendPeriod;
  spends: SpendEntry[];
  /** keyed by statement date */
  bills: Record<Ymd, { paidAt: string }>;
  /** keyed by fee date */
  fees: Record<Ymd, { status: "waived" | "paid"; at: string }>;
  addedAt: string;
}

export interface Settings {
  centsPerMile: number;
  billReminderDays: number;
  feeReminderDays: number;
  notifications: boolean;
}

export interface UserState {
  version: 1;
  myCards: MyCard[];
  /** personal notes, keyed by catalogue card id */
  notes: Record<string, string>;
  settings: Settings;
  lastBackupAt?: string;
}

export const DEFAULT_SETTINGS: Settings = {
  centsPerMile: 1.5,
  billReminderDays: 7,
  feeReminderDays: 7,
  notifications: false,
};

export const emptyState = (): UserState => ({
  version: 1,
  myCards: [],
  notes: {},
  settings: { ...DEFAULT_SETTINGS },
});
