// -- catalogue (public/catalog.json, generated by scripts/prepare-data.mjs) ----------------------

export type RewardKind = "miles" | "cashback" | "points";
export type RateUnit = "percent" | "mpd" | "points_per_dollar";
export type Period =
  | "transaction"
  | "statement_month"
  | "calendar_month"
  | "quarter"
  | "membership_year"
  | "calendar_year";

export interface Rule {
  id: string;
  label: string;
  rate: number;
  unit: RateUnit;
  tier: "base" | "bonus";
  allSpend: boolean;
  desc: string | null;
  minSpend: number | null;
  minSpendPeriod: Period | null;
  maxSpend: number | null;
  maxSpendPeriod: Period | null;
  cap: { amount: number; unit: "SGD_spend" | "SGD_cashback" | "miles" | "points"; period: Period } | null;
  modes: string[];
  conditions: string[];
}

export interface CatalogCard {
  id: string;
  bank: string;
  name: string;
  network: string | null;
  image: string | null;
  url: string | null;
  kind: RewardKind;
  currency: string;
  fee: { amount: number; firstYearWaived: boolean | null } | null;
  income: number | null;
  rules: Rule[];
  coverage: Record<string, { level: string; rules: string[] }>;
  bonuses: { by: string; desc: string; value: number | null; validTo: string | null; url: string | null }[];
  notes: string[];
  status: "draft" | "reviewed" | "stale";
  sources: { url: string; type: string; title: string | null }[];
}

export interface Category {
  key: string;
  label: string;
  parent: string | null;
  group: boolean;
}

export interface Catalog {
  builtAt: string;
  categories: Category[];
  cards: CatalogCard[];
}

// -- user data (stored on the device) ---------------------------------------------------------

/** Calendar dates are local 'YYYY-MM-DD' strings throughout. */
export type Ymd = string;

export interface SpendEntry {
  id: string;
  date: Ymd;
  amount: number;
  note?: string;
}

export interface MyCard {
  id: string;
  catalogId?: string;
  nickname: string;
  last4?: string;
  /** day of month the statement is issued (1–31, clamped to month length) */
  statementDay?: number;
  /** day of month payment is due; falls in the month after the statement if ≤ statementDay */
  dueDay?: number;
  /** annual fee billing date, 'MM-DD' */
  feeDate?: string;
  minSpend?: number;
  maxSpend?: number;
  /** spend tracking resets on the statement date, or on the 1st */
  spendPeriod: "statement" | "calendar";
  spends: SpendEntry[];
  /** keyed by statement date */
  bills: Record<Ymd, { paidAt: string }>;
  /** keyed by fee date */
  fees: Record<Ymd, { status: "waived" | "paid"; at: string }>;
  addedAt: string;
}

export interface Settings {
  centsPerMile: number;
  billReminderDays: number;
  feeReminderDays: number;
  notifications: boolean;
}

export interface UserState {
  version: 1;
  myCards: MyCard[];
  /** personal notes, keyed by catalogue card id */
  notes: Record<string, string>;
  settings: Settings;
  lastBackupAt?: string;
}

export const DEFAULT_SETTINGS: Settings = {
  centsPerMile: 1.5,
  billReminderDays: 7,
  feeReminderDays: 7,
  notifications: false,
};

export const emptyState = (): UserState => ({
  version: 1,
  myCards: [],
  notes: {},
  settings: { ...DEFAULT_SETTINGS },
});
